-- web(단거주의보) 앱이 기대하는 평면 읽기 모델.
--
-- 앱은 PostgREST embed(`cafes:cafe_id(*)`, `categories (*)`)를 쓰기 때문에 실제 FK 가 필요하다.
-- 뷰로는 관계 추론이 보장되지 않아 실 테이블로 만들고, 정규화 테이블에서 채워 넣는다.
-- 쓰기 주체는 refresh_web_read_model() 하나뿐이다.

CREATE TABLE "cafes" (
	"id" text PRIMARY KEY,
	"name_kor" text NOT NULL,
	"name_eng" text NOT NULL DEFAULT '',
	"logo_url" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL DEFAULT now()
);--> statement-breakpoint

CREATE TABLE "categories" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"source_id" text NOT NULL UNIQUE,
	"name" text NOT NULL,
	"type" text NOT NULL DEFAULT '',
	"cafe_id" text NOT NULL REFERENCES "cafes"("id") ON DELETE CASCADE,
	"sort_order" integer NOT NULL DEFAULT 0
);--> statement-breakpoint

CREATE TABLE "menus" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"source_key" text NOT NULL UNIQUE,
	"cafe_id" text NOT NULL REFERENCES "cafes"("id") ON DELETE CASCADE,
	"category_id" integer NOT NULL REFERENCES "categories"("id") ON DELETE CASCADE,
	"name_kor" text NOT NULL,
	"name_eng" text NOT NULL DEFAULT '',
	"description" text NOT NULL DEFAULT '',
	"is_seasonal" boolean NOT NULL DEFAULT false,
	"image_url" text,
	"size_name" text NOT NULL DEFAULT '',
	"serving_size" numeric(10, 2),
	"serving_unit" text,
	"calories" numeric(10, 2),
	"carbohydrate" numeric(10, 2),
	"sugars" numeric(10, 2),
	"protein" numeric(10, 2),
	"fat" numeric(10, 2),
	"saturated_fat" numeric(10, 2),
	"trans_fat" numeric(10, 2),
	"sodium" numeric(10, 2),
	"caffeine" numeric(10, 2),
	"allergens" text[] NOT NULL DEFAULT '{}',
	"sort_order" integer NOT NULL DEFAULT 0
);--> statement-breakpoint

CREATE INDEX "categories_cafe_id_idx" ON "categories" ("cafe_id");--> statement-breakpoint
CREATE INDEX "menus_cafe_id_idx" ON "menus" ("cafe_id");--> statement-breakpoint
CREATE INDEX "menus_category_id_idx" ON "menus" ("category_id");--> statement-breakpoint

-- 공개 읽기 전용 (0002 와 동일 정책)
REVOKE ALL ON TABLE "cafes" FROM anon, authenticated;--> statement-breakpoint
REVOKE ALL ON TABLE "categories" FROM anon, authenticated;--> statement-breakpoint
REVOKE ALL ON TABLE "menus" FROM anon, authenticated;--> statement-breakpoint
GRANT SELECT ON TABLE "cafes" TO anon, authenticated;--> statement-breakpoint
GRANT SELECT ON TABLE "categories" TO anon, authenticated;--> statement-breakpoint
GRANT SELECT ON TABLE "menus" TO anon, authenticated;--> statement-breakpoint
ALTER TABLE "cafes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "menus" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "cafes_public_select" ON "cafes" FOR SELECT TO anon, authenticated USING (true);--> statement-breakpoint
CREATE POLICY "categories_public_select" ON "categories" FOR SELECT TO anon, authenticated USING (true);--> statement-breakpoint
CREATE POLICY "menus_public_select" ON "menus" FOR SELECT TO anon, authenticated USING (true);--> statement-breakpoint

CREATE OR REPLACE FUNCTION refresh_web_read_model() RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
	-- 1) cafes
	INSERT INTO cafes (id, name_kor, name_eng, logo_url)
	SELECT
		c.id,
		c.name,
		coalesce(c.description, ''),
		coalesce(c.logo_url, '/logos/' || c.id || '.svg')
	FROM cafe c
	WHERE c.is_active
	ON CONFLICT (id) DO UPDATE SET
		name_kor = EXCLUDED.name_kor,
		name_eng = EXCLUDED.name_eng,
		logo_url = EXCLUDED.logo_url;

	DELETE FROM cafes
	WHERE id NOT IN (SELECT c.id FROM cafe c WHERE c.is_active);

	-- 2) categories — 메뉴가 실제로 달린 카테고리만. (음료/푸드 같은 루트는 칩으로 띄워도 빈 목록이 된다)
	INSERT INTO categories (source_id, name, type, cafe_id, sort_order)
	SELECT
		cc.id,
		cc.name,
		coalesce(parent.name, ''),
		cc.cafe_id,
		cc.sort_order
	FROM cafe_category cc
	LEFT JOIN cafe_category parent ON parent.id = cc.parent_id
	WHERE cc.is_visible
		AND EXISTS (SELECT 1 FROM menu m WHERE m.category_id = cc.id)
	ON CONFLICT (source_id) DO UPDATE SET
		name = EXCLUDED.name,
		type = EXCLUDED.type,
		cafe_id = EXCLUDED.cafe_id,
		sort_order = EXCLUDED.sort_order;

	DELETE FROM categories
	WHERE source_id NOT IN (
		SELECT cc.id FROM cafe_category cc
		WHERE cc.is_visible AND EXISTS (SELECT 1 FROM menu m WHERE m.category_id = cc.id)
	);

	-- 3) menus — 사이즈(menu_variant)별 1행
	CREATE TEMP TABLE _menu_src ON COMMIT DROP AS
	SELECT
		cc.id
			|| '|' || m.name
			|| '|' || mv.name
			|| CASE
				WHEN row_number() OVER (
					PARTITION BY cc.id, m.name, mv.name ORDER BY m.sort_order, mv.sort_order, m.id, mv.id
				) > 1
				THEN '#' || row_number() OVER (
					PARTITION BY cc.id, m.name, mv.name ORDER BY m.sort_order, mv.sort_order, m.id, mv.id
				)::text
				ELSE ''
			END AS source_key,
		cc.cafe_id,
		cat.id AS category_id,
		-- 사이즈가 여러 개인 메뉴만 이름 뒤에 사이즈를 붙여 목록에서 구분한다
		CASE WHEN vc.cnt > 1 THEN m.name || ' (' || mv.name || ')' ELSE m.name END AS name_kor,
		coalesce(m.description, '') AS description,
		m.image_url,
		mv.name AS size_name,
		mv.size AS serving_size,
		mv.unit AS serving_unit,
		mv.calories, mv.carbohydrate, mv.sugars, mv.protein, mv.fat,
		mv.saturated_fat, mv.sodium, mv.caffeine,
		coalesce(
			(
				SELECT array_agg(btrim(t) ORDER BY ord)
				FROM unnest(string_to_array(m.allergens, ',')) WITH ORDINALITY AS u(t, ord)
				WHERE btrim(t) <> '' AND btrim(t) <> '-'
			),
			'{}'::text[]
		) AS allergens,
		m.sort_order * 1000 + mv.sort_order AS sort_order
	FROM menu m
	JOIN cafe_category cc ON cc.id = m.category_id
	JOIN categories cat ON cat.source_id = cc.id
	JOIN menu_variant mv ON mv.menu_id = m.id
	JOIN (SELECT menu_id, count(*) AS cnt FROM menu_variant GROUP BY menu_id) vc ON vc.menu_id = m.id;

	INSERT INTO menus (
		source_key, cafe_id, category_id, name_kor, description, image_url,
		size_name, serving_size, serving_unit,
		calories, carbohydrate, sugars, protein, fat, saturated_fat, sodium, caffeine,
		allergens, sort_order
	)
	SELECT
		source_key, cafe_id, category_id, name_kor, description, image_url,
		size_name, serving_size, serving_unit,
		calories, carbohydrate, sugars, protein, fat, saturated_fat, sodium, caffeine,
		allergens, sort_order
	FROM _menu_src
	ON CONFLICT (source_key) DO UPDATE SET
		cafe_id = EXCLUDED.cafe_id,
		category_id = EXCLUDED.category_id,
		name_kor = EXCLUDED.name_kor,
		description = EXCLUDED.description,
		image_url = EXCLUDED.image_url,
		size_name = EXCLUDED.size_name,
		serving_size = EXCLUDED.serving_size,
		serving_unit = EXCLUDED.serving_unit,
		calories = EXCLUDED.calories,
		carbohydrate = EXCLUDED.carbohydrate,
		sugars = EXCLUDED.sugars,
		protein = EXCLUDED.protein,
		fat = EXCLUDED.fat,
		saturated_fat = EXCLUDED.saturated_fat,
		sodium = EXCLUDED.sodium,
		caffeine = EXCLUDED.caffeine,
		allergens = EXCLUDED.allergens,
		sort_order = EXCLUDED.sort_order;

	DELETE FROM menus WHERE source_key NOT IN (SELECT source_key FROM _menu_src);

	DROP TABLE _menu_src;
END;
$$;--> statement-breakpoint

SELECT refresh_web_read_model();
